### ISSUE TITLE
Not working anymore with Chrome

### ISSUE THREAD

**Issue by ot3kcw6c** [qlik-oss/catwalk#505]
We don't know if this issue occur with a Qlik Sense upgrade or a newer Chrome version.
Catwalk 1.0.0 (local)
Qlik Sense Enterprise Februar2021 Patch2/May2021 Preview
Chrome Version 90.0.4430.212 (Offizieller Build) (32-Bit)
->Not working

Tested with Firefox 84.0.2 (64-Bit) -> working

Error: Not connected
    at RPC.send (http://server-671.mycompany.com:1234/src.78399e21.js:29547:23)
    at http://server-671.mycompany.com:1234/src.78399e21.js:28733:37

**Comment by alex-almagro** [comment]
Sorry for the delay in the response.

Please refer to this page: https://community.qlik.com/t5/Knowledge-Base/Missing-SameSite-attribute-blocks-requests-in-Chrome-80-and/ta-p/1712551?_ga=2.56338347.1605537249.1626354969-2104403980.1589915842

The issue can be fixed by setting the SameSite cookies to None, as stated in the link. I am closing this issue, but feel free to re-open if the problem has not been solved.
