### ISSUE TITLE
HyperCube builder dialog scrolls inverse.

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/catwalk#90]
When pressing the + sign in the bottom right corner. The list with fields, dimensions and measures that appears is scrolled to the bottom. So to see additional items you have to scroll upwards as opposed to downwards.

The list is also sorted inverted.

**Comment by hrigner** [comment]
It's by design - the list is opened bottom up. Give us a great motivation why this is an issue, and we will consider changing it :)

**Comment by mindspank** [comment]
1) Took me a few minutes to understand I could actually scroll.
2) I would argue that unless we have a really really good reason for introducing a new UI pattern that noone else is using we should avoid breaking well established UI design paradigms.

**Comment by snurrfint** [comment]
Thanks for pointing this out. It was not clear to me that this reverse layout direction is confusing. I thought most people was used to it since almost all messaging apps are doing it this way.

![screen shot 2018-11-29 at 10 36 45](https://user-images.githubusercontent.com/15340325/49212682-e9695700-f3c2-11e8-9169-86278638ae26.png)
This is from facebook. So there is definitely products that sort the list bottom to top but its not that common honestly.

Sense is always doing it from top to bottom. I guess it's kind of dumb to change that. I'll go ahead and change it for that reason.

You want the input field at the top too or is it ok to just reverse the scroll order?

**Comment by snurrfint** [comment]
https://github.com/qlik-oss/catwalk/pull/118

**Comment by hrigner** [comment]
Closed with #118

**Comment by hrigner** [comment]
Closed with #118
